package FrontEnd;


import javax.swing.JOptionPane;
import BackEnd.FullscreenFrame;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Geff
 */
public class home_Dashboard extends javax.swing.JFrame {
    private static final String ADMIN_PASSWORD = "admin123";
    /**
     * Creates new form home
     */
    public home_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recentTransactions1 = new javax.swing.JLabel();
        recentTransactions = new javax.swing.JLabel();
        inventory = new javax.swing.JLabel();
        addSales = new javax.swing.JLabel();
        addSales1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        inventory1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recentTransactions1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentTransactions1MouseClicked(evt);
            }
        });
        jPanel1.add(recentTransactions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 200, 40));

        recentTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentTransactionsMouseClicked(evt);
            }
        });
        jPanel1.add(recentTransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 400, 70));

        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
        });
        jPanel1.add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 110, 40));

        addSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSalesMouseClicked(evt);
            }
        });
        jPanel1.add(addSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 140, 40));

        addSales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSales1MouseClicked(evt);
            }
        });
        jPanel1.add(addSales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 360, 90));

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 110, 70, 40));

        inventory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventory1MouseClicked(evt);
            }
        });
        jPanel1.add(inventory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 240, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recentTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentTransactionsMouseClicked
        dispose(); 
        new transactions_Dashboard().setVisible(true); 
    }//GEN-LAST:event_recentTransactionsMouseClicked

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
        new verification().setVisible(true);
    }//GEN-LAST:event_inventoryMouseClicked

    private void addSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSalesMouseClicked
        dispose();
        new addSales_Dashboard().setVisible(true);
    }//GEN-LAST:event_addSalesMouseClicked

    private void recentTransactions1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentTransactions1MouseClicked
       dispose();
        new transactions_Dashboard().setVisible(true);
    }//GEN-LAST:event_recentTransactions1MouseClicked

    private void addSales1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSales1MouseClicked
        dispose();
        new addSales_Dashboard().setVisible(true);
    }//GEN-LAST:event_addSales1MouseClicked

    private void inventory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventory1MouseClicked
//        dispose();
//        new inventory_Dashboard().setVisible(true);
          new verification().setVisible(true);
    }//GEN-LAST:event_inventory1MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
       int a=JOptionPane.showConfirmDialog(null, "Do you really want to Logout?", "Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if (a==0){
            dispose();
            new loginPage_Dashboard().setVisible(true);
        }  
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_Dashboard().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addSales;
    private javax.swing.JLabel addSales1;
    private javax.swing.JLabel inventory;
    private javax.swing.JLabel inventory1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel recentTransactions;
    private javax.swing.JLabel recentTransactions1;
    // End of variables declaration//GEN-END:variables
}